### ISSUE TITLE
repetita iuvant..... ma solo gli altri ;)

### ISSUE THREAD

**Issue by pnicorelli** [Marcog1t/php_sql#3]
```
$link = mysql_connect('localhost', 'marcowebwork', '');
```

immagina di dover spostare il sito... dovresti aprire tutte le pagine e modificare quella linea...
cerca di mettere la connessione in un posto unico e poi andarla ad includere dove serve

**Comment by Marcog1t** [comment]
allora...
-ho sistemato il problema dell'apice con il comando " get_magic_quotes_gpc "
-ho sistemato le sessioni in modo da non poter visualizzare pagine diverse da log.php se non si ha una sessione attiva
-ho spostato in un file a parte i dati di connessione includendoli nei fogli necessari
adesso sto cercando di far funzionare mysql_fetch_assoc() .

**Comment by pnicorelli** [comment]
ok, fai la push delle mofiche nel repository online ;)

**Comment by Marcog1t** [comment]
ciao, scusa il ritardo ma sono arrivato adesso dall'agenzia, mi metto a
lavoro per il comando mysql_fetch_assoc . gli altri file aggiornati sono
qua https://github.com/Marcog1t/php_sql

2015-07-06 18:55 GMT+02:00 Paolo Willy Nicorelli notifications@github.com:
